### PR TITLE
Add surface derivatives to plugin

### PR DESCRIPTION
**Pull request by lehtonenp**
This is a draft PR to view surface derivatives code style and implementation.

### CODE REVIEW

**Review by nmaarnio — CHANGES_REQUESTED** [review]
This looks good structurally overall and mostly correct when it comes to how processing algorithms should be implemented! However, this does not reflect the EIS Toolkit CLI function for surface derivatives, but instead the _toolkit_ functions. Processing algorithm must match to the CLI function. Please take a look the `surface_derivatives_cli` function found in the `cli.py` file in EIS Toolkit and create a matching processing algorithm. The `classify_aspect` can stay and is a separate one, but there is a minor issue there: `QgsProcessingParameterEnum` takes str values as options, not ints (even if the options represent numbers). Currently, QGIS throws a Python error when the plugin is loaded.

**Comment by lehtonenp** [comment]
Thank you for the feedback! I assumed that the first order, second order and classify aspect were required to be implemented as plugin functions. Now, I see that the higher order `surface_derivatives_cli` is implemented instead into the plugin. Did I understand correctly?

**Comment by nmaarnio** [comment]
Yes. This one is a bit unusual case as usually the toolkit functions match closely to the CLI implementation 😅. After some discussion with Micha, who implemented the surface derivative functions, we decided to simplify and streamline the way they are called in QGIS by combining first and second order functions into one (a bit more heavily parameterized) function.

There are some cases where a CLI functions execute two or more toolkit functions (for example data transformations before the "main" tool), and this is why the CLI function should always be looked at when implementing processing algorithms in our plugin.

**Comment by nmaarnio** [comment]
A quick comment here: The "description" field of each algorithm is actually the displayed name of the algorithm, and not a help string. It is unfortunately one of the misleading parameter names in QGIS. To add help strings to the algorithm parameters, we need to call `setHelp` method for the parameters (this has not been done so far in any implementation, but should be added eventually).

**Comment by lehtonenp** [comment]
> A quick comment here: The "description" field of each algorithm is actually the displayed name of the algorithm, and not a help string. It is unfortunately one of the misleading parameter names in QGIS. To add help strings to the algorithm parameters, we need to call `setHelp` method for the parameters (this has not been done so far in any implementation, but should be added eventually).

I used [gdal](https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/gdal/ogr2ogr.py) for reference in making the plugin work with the setHelp method. I could not call the function on initialization of QgsProcessingParameters.

**Comment by nmaarnio** [comment]
There was an issue with missing logic for enum parameters with multiple values. I added that and now this works, except that the produced layers are not automatically loaded since their number and namings are currently unknown to the algorithm definition. This is an issue that affects a few other algorithms too, and I think thinking it through needs a bit time and its better to handle them all at once. So I think this is in good enough state for merging.

**Review by nmaarnio — APPROVED** [review]

**Pull request merged**
